FROM node:18-alpine

# Working directory be src
WORKDIR /src

COPY package.json ./

###  Installing dependencies
RUN yarn install --silent
# copy local files to app folder
COPY . .
CMD ["yarn","run","dev"]